name: Runner Selection Test
on:
  workflow_dispatch:
    inputs:
      custom_runner:
        type: string
  workflow_call:
    inputs:
      custom_runner:
        type: string
  push:
    branches: [ main ]
env:
  # If runner is given via input param then use this custom runner
  # Otherwise check if the variable that specifies the runner label is defined, if so use this variable value
  # If nothing given use the "ubuntu-latest" as default
  # the sh_runner_gh_ubuntu_latest var shall be defined on org level ideally
  runner_label: |-
    ${{ case(
      inputs.custom_runner != '', inputs.custom_runner,
      vars.sh_runner_gh_ubuntu_latest != '', vars.sh_runner_gh_ubuntu_latest,
      'ubuntu-latest'
      )
    }}
jobs:
  prepare:
    name: Prepare job to compute runner label
    outputs:
      runner_label: ${{ steps.compute-runner-label.outputs.runner_label }}
    runs-on: "ubuntu-slim"
    steps:
      - name: Compute runner label
        id: compute-runner-label
        run: |
          # ...
          echo "runner_label=${{ env.runner_label }}" >> $GITHUB_OUTPUT

  use-label-from-prepare:
    name: Use runner label from prepare job
    needs: prepare
    #runs-on: ${{ inputs.runner_label }}
    runs-on: ${{ needs.prepare.outputs.runner_label }}
    steps:
      - run: |
          env
          echo "Hello World"

  use-input-or-var:
    name: Use input or var as rununer
    # If runner is given via input param then use this custom runner
    # Otherwise check if the variable that specifies the runner label is defined, if so use this variable value
    # If nothing given use the "ubuntu-latest"
    # the sh_runner_gh_ubuntu_latest var shall be defined on org level ideally
    runs-on: |-
      ${{ case(
        inputs.custom_runner != '', inputs.custom_runner,
        vars.sh_runner_gh_ubuntu_latest != '', vars.sh_runner_gh_ubuntu_latest,
        'ubuntu-latest'
        )
      }}
    steps:
      - run: |
          env
          echo "Hello World "
  use-json-var:
    name: Use json var
    # If runner is given via input param then use this custom runner
    # Otherwise check if the variable that specifies the runner label is defined, if so use this variable value
    # If nothing given use the "ubuntu-latest"
    # the sh_runner_gh_ubuntu_latest var shall be defined on org level ideally
    runs-on: |-
      ${{ case(
        inputs.custom_runner != '', inputs.custom_runner,
        vars.json_runner_labels != '', fromJSON(vars.json_runner_labels),
        'ubuntu-latest'
        )
      }}
    steps:
      - run: |
          env
          echo "Hello World "
#  use-env:
#    name: Use env var as rununer
# Using an env var here is not supported !
#    runs-on: ${{ env.runner_label }}
#    steps:
  matrix-job-test:
    # Matrix json object with resolved runner labels can also be generated in a prepare job
    strategy:
        matrix: 
          run: 
             - app: 'app1'
               runner: ${{ case(
                        inputs.custom_runner != '', inputs.custom_runner,
                        vars.sh_runner_gh_ubuntu_latest != '', vars.sh_runner_gh_ubuntu_latest,
                        'ubuntu-latest'
                        )
                      }}
             - app: 'app2'
               runner: ubuntu-slim
    runs-on: ${{ matrix.run.runner }}
    timeout-minutes: 60
    steps:
      - run: echo ${{ matrix.run.app }}

#      - run: |
#          echo "Hello World on runner: ${{ inputs.runner_label }}"
